export const skills = [
    "Java",
    "Android Studio",
    "Objective C",
    "C++",
    "С",
    "SQL",
    "C#",
    "Android SDK",
    "Material Design",
    "GMS",
    "Multi-threading",
    "cocos2d-x",
    "Boost",
    "STL",
    "SOAP",
    "JSON",
    "JSON",
    "REST",
    "SCRUM",
    "ORM",
    "GIT",
    "JIRA",
    "Target Process",
    "Kotlin",
    "Swift",
    "Flutter/Dart",
];

export const departments = [
    "Тестирование",
    "Дизайн",
    "Android разработка",
    "iOS разработка",
    "Back-end",
    "Front-end",
    "Продажи RU",
    "Продажи Global",
    "Управление проектами",
];
